name = "AtmosphericModels"
uuid = "c59cac55-771d-4f45-b14d-1c681463a295"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.2.3"

[deps]
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"

[compat]
HypergeometricFunctions = "0.3"
KiteUtils = "0.6, 0.7, 0.8"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Remez = "2e7db186-766a-50e7-8928-5c30181fb135"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools", "Remez"]
