name = "AtmosphericModels"
uuid = "f37ff129-77a9-45f4-853e-becb2e3e1f01"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
